---

- hosts: all
  become: true

  vars:
    com_redhat_ntp:
      ntp_servers:
        - hostname: "foo.example.com"
          pool: true
          minpoll: 6
          maxpoll: 10
          iburst: true

        - hostname: "bar.example.com"
          pool: false
          minpoll: 4
          maxpoll: 6
          iburst: false

    com_redhat_tuned:
      profile: "powersave"

  roles:
    - system-api
    - com_redhat_ntp
    - com_redhat_tuned
    - com_redhat_kdump

