- hosts: localhost
  vars:
    firewall:
      - { service: [ 'tftp', 'ftp' ],
          port: [ '443/tcp', '443/udp' ],
          trust: [ 'eth1', 'eth3' ],
          masq: [ 'eth2', 'eth4' ],
          forward_port: [ 'eth0;447/tcp;;1.2.3.4', 'eth0;448/tcp;;1.2.3.5' ],
          state: 'enabled' }
      - { service: 'tftp', state: 'enabled' }
      - { port: '443/tcp', state: 'enabled' }
      - { trust: 'eth1', state: 'enabled' }
      - { trust_by_mac: '00:11:22:33:44:55', state: 'enabled' }
      - { masq: 'eth1', state: 'enabled' }
      - { masq_by_mac: '00:11:22:33:44:55', state: 'enabled' }
      - { forward_port: 'eth0,445/tcp,,1.2.3.4', state: 'enabled' }
      - { forward_port_by_mac: '00:11:22:33:44:55,445/tcp,,1.2.3.4', state: 'enabled' }
  roles:
    - firewall
